### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by bduff9** [SassDoc/sass-convert#21]
I have a project I am trying to use this in, however, it fails with the following error:
```
convert error TypeError: file.pipe is not a function
    at Converter.convertFile (C:\my-project\node_modules\sass-convert\dist\index.js:288:12)
    at C:\my-project\node_modules\sass-convert\dist\index.js:353:23
    at tryCatch (C:\my-project\node_modules\es6-promise\dist\es6-promise.js:410:12)
    at invokeCallback (C:\my-project\node_modules\es6-promise\dist\es6-promise.js:425:13)
    at publish (C:\my-project\node_modules\es6-promise\dist\es6-promise.js:393:7)
    at flush (C:\my-project\node_modules\es6-promise\dist\es6-promise.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn sass-convert ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

I am just using the basic script from your readme:
```
const vfs = require('vinyl-fs');
const converter = require('sass-convert');

vfs.src(['./**/*.sass'])
	.pipe(converter({
		from: 'sass',
		to: 'scss',
	}))
	.on('error', err => console.log('convert error', err))
	.pipe(vfs.dest('./output'))
	.on('error', err => console.log('save error', err));
```

Any help would be appreciated!

**Comment by jr-cologne** [comment]
Hi @pascalduez,

First of all, sorry for interfering here, even though the Issue is actually already closed.

I'm also getting a similar error using your example scripts with Gulp 4.

I would appreciate any kind of help very much. I guess, it's in your own interst to find and fix bugs even if some people are not always polite. Furthermore, this package is basically the only thing I found in order to convert sass to scss. So, I'm really hoping to find someone who can help me.

Here is the error:

```
TypeError: file.pipe is not a function
    at Converter.convertFile (path\to\project\node_modules\sass-convert\dist\index.js:288:12)
    at path\to\project\node_modules\sass-convert\dist\index.js:353:23
    at tryCatch (path\to\project\node_modules\es6-promise\dist\es6-promise.js:410:12)
    at invokeCallback (path\to\project\node_modules\es6-promise\dist\es6-promise.js:425:13)
    at publish (path\to\project\node_modules\es6-promise\dist\es6-promise.js:393:7)
    at flush (path\to\project\node_modules\es6-promise\dist\es6-promise.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

And that's my code:

```js
const gulp = require('gulp');
const sass = require('gulp-sass');
const fs = require('fs');
const vfs = require('vinyl-fs');
const source = require('vinyl-source-stream');
const convert = require('sass-convert');
const rename = require('gulp-rename');

gulp.task('scss', () => {
  return fs.createReadStream('src/sass/file.sass')
    .pipe(source('file.sass'))
    .pipe(convert({
      from: 'sass',
      to: 'scss'
    }))
    .pipe(rename('file.scss'))
    .pipe(vfs.dest('src/scss'));
});
```

I also tried the first example which @bduff9 is using. It's essentially the same error.

Thank you in advance for any reply!

Best regards,
@jr-cologne

**Comment by pascalduez** [comment]
Please check the other issues on this repo, there are already reports of problems under windows.
Fact is the team don't have an easy way to debug this on windows at hand, and also lacking a bit of interest. So any help is welcome.

**Comment by jr-cologne** [comment]
Alright, @pascalduez.
If sass-convert is actually outdated, I'm going to look for a different solution.

I guess I don't really have the knowledge to help you out, though I would be happy to help.

Thanks anyway!
